### PR TITLE
Dark mode fixes

### LINKED ISSUE #65: Small dark theme fixes.
Some things don't look nice yet because of hard coded colors.

- [x] The background color for the disabled extra actions buttons don't look right.
- [ ] The selected color is almost invisible for:
  - [ ] The main device page.
  - [ ] The nicknames page.
  - [ ] The Vive Base stations ids.
- [x] Use light Github logo instead of dark one in section About on settings page.

### PR DESCRIPTION
**Pull request by mralext20**
closes #65 

i do not have any vive basestations to test those features. can you check, @jeroen1602 ?

### CODE REVIEW

**Comment by jeroen1602** [comment]
I also don't have any Vive base stations, their support is completely theoretical. You can enable getting fake devices in the list for testing by going to `lib/main.dart` and removing the comment on line 26 (don't forget to import the `FakeBLEBackend`.

But I'll have a look at it.

**Review by jeroen1602 — COMMENTED** [review]
It's looking good. Could you also change the selected background for the main devices page, the nicknames page and the Vive Base station ids page. (For the Nickname page and the Vive Base station ids page you can tap the 🚫 10 times to generate fake data (debug only)).

I'm not sure what to change the background color to because `Theme.of(context).selectedRowColor` doesn't look good in dark mode.

**Comment by BlakCake** [comment]
I have Vive Base Stations so maybe I can help?

**Comment by jeroen1602** [comment]
@BlakCake that is great! can we continue this conversation in #15?

**Review by jeroen1602 — APPROVED** [review]
Great job! Thanks for the help.

**Pull request merged**
