### PR TITLE
(first) iOS build and updated iOS AppIconSet

### PR DESCRIPTION
**Pull request by HeLau1337**
See comments on issue #26

PS: Am I doing this right? I've used GitHub and Pull Requests before (in projects where I am a contributor with permission to change the original repo). But I've never forked a repo and then opened a pull request. So let me know if there's anything I should do differently.

### CODE REVIEW

**Comment by jeroen1602** [comment]
It's looking good. I see that xcode changed a lot of files, so I had a look if some of them may need to be in the `.gitignore` file and I [found](https://stackoverflow.com/questions/61994014/should-last-build-id-be-commited) that we should update the `.gitignore` file with:

```.gitignore
*.last_build_id
```

Can you please update your PR to add this?

**Comment by HeLau1337** [comment]
Sure, I'm going to update it.
Looking back, I should have paid attention to which of these files should be in gitignore myself.

**Comment by jeroen1602** [comment]
Can you also update the `changelog.md`?

**Comment by HeLau1337** [comment]
I also changed the "display name" in iOS:
Screenshot 2020-09-05 at 19 48 41

You can see the old display name in my previous screenshot(s) [here].(https://github.com/jeroen1602/lighthouse_pm/issues/26#issuecomment-687436995)

**Review by jeroen1602 — APPROVED** [review]
Good job, I'm going to merge it now!

**Pull request merged**
