### PR TITLE
user System theme for dark mode

### PR DESCRIPTION
**Pull request by mralext20**
simply by adding a darkTheme: ThemeData.dark() to the MaterialApp init function.

i'll post some screenshots of darkmode here:

### CODE REVIEW

**Comment by mralext20** [comment]
closes #9 (?) i think you wanted to have a userdefinable dark mode toggle in app aswell for people on devices that dont support system wide darkmode. (android 10 / API 29+ https://developer.android.com/guide/topics/ui/look-and-feel/darktheme )

**Review by jeroen1602 — CHANGES_REQUESTED** [review]
Adding support for this was easier than I thought it would be.

Also can you update `CHANGELOG.md` with the new feature?

**Comment by jeroen1602** [comment]
And yes I do want to add a toggle in settings for the dark theme change, but I think that can be a separate issue and pr.

The toggle would have 2 or 3 options depending on the version of the OS. `Light mode`, `Dark mode` and `System default` (if the system can report the preferred type).

**Comment by mralext20** [comment]
this article on medium helped me figure this out. flutter is an interesting language! 

https://medium.com/@pmutisya/dark-mode-in-flutter-3742062f9f59

**Review by jeroen1602 — COMMENTED** [review]
:+1:

**Review by jeroen1602 — APPROVED** [review]

**Pull request merged**
